In [4]:
import numpy as np
import time

In [5]:
arr = np.array([1,2,3,4,5,6])
print(arr, type(arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [6]:
size = 1_000_000

#Python List
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python list time = {end - start}")


#Numpy Arrays
np_arr = np.array(py_list)
start = time.time()

#vectorization
sq_array = np_arr ** 2
end = time.time()
print(f"NumPy Array time = {end - start}")

Python list time = 0.04289364814758301
NumPy Array time = 0.0021331310272216797


In [7]:
import sys

print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"Python Array size = {np_arr.nbytes} bytes")

Python list size = 8000056000000 bytes
Python Array size = 8000000 bytes


In [12]:
#create - from list
arr1 = np.array([1,2,3,4,5,6])
print(arr1, type(arr1), arr1.dtype)

arr2 = np.array([1,2,3,4,5,"Array"])
print(arr2, type(arr2), arr2.shape, arr2.dtype)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'Array'] <class 'numpy.ndarray'> (6,) <U21


In [31]:
#Create
arr3 = np.zeros((2,3) , dtype="int64") #prefill
print(arr3, arr3.shape)

arr4 = np.ones((2,) , dtype="int64") #prefill
print(arr4, arr4.shape)

arr5 = np.full((3,4), 100) #prefill with value
print(arr5, arr5.shape)

arr6 = np.eye(3, dtype="int64") #identity matrix
print(arr6, arr6.shape)

arr7 = np.arange(1,10,2) #range elements
print(arr7, arr7.shape)

arr8 = np.linspace(1,100,4, dtype="int64") #evenly spaced arrays
print(arr8, arr8.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1] (2,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 3 5 7 9] (5,)
[  1  34  67 100] (4,)


In [39]:
#Properties
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr.shape) #dimensions
print(arr.size) #tot elements
print(arr.dtype) # data types
print(arr.ndim) #no. of dimensions

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(2, 5)
10
int64
2
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]] float64


In [45]:
#Operations on arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape) #dimensions

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape) #dimensions

flattened = arr.flatten() #2D --> 1D
print(flattened, flattened.shape) #dimensions

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [48]:
#Fancy Indexing 
arr = np.array([1,2,3,4,5])

# arr[0] = 19
# print(arr[0])

idx = [1,2,4]
print(arr[idx])

#Boolean Indexing
print(arr[arr > 3])

[2 3 5]
[4 5]


In [49]:
#Slicing 
arr = np.array([1,2,3,4,5])

print(arr[1:3])

[2 3]


In [61]:
#Copy and View
# Copy vs View

nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list, nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3]
sub_arr2 = arr[1:3].copy()
print(sub_arr)
sub_arr[0] = 200
sub_arr2[1] = 300

print(sub_arr, arr ,sub_arr2)

[2, 3]
[200, 3] [1, 2, 3, 4, 5]
[2 3]
[200   3] [  1 200   3   4   5] [  2 300]
